const stats=[["10K+","Happy Kids"],["50+","Yoga Poses"],["2","YouTube Channels"],["100%","Pure Joy"]];
export default function AboutPage(){return <main className="about-page-new">
  <header className="site-header"><a className="brand" href="/"><img src="/assets/yoga-soda-pop-logo-transparent.png" alt="Yoga Soda Pop" /></a><nav><a href="/">Home</a><a href="/kids">Kids</a><a href="/beats">Beats</a><a href="/shop">Shop <span>Soon</span></a><a className="active about-active" href="/about">About</a></nav></header>
  <section className="about-banner"><div><p className="eyebrow">✧ Our story</p><h1>Yoga. Music. Joy.</h1><p>Yoga Soda Pop is a bubbly universe where movement, music, and creativity collide. We make yoga fun for kids, beats that move you, and digital tools that bring it all to life.</p></div></section>
  <section className="about-origin"><div><h2>Where it all began</h2><p>Yoga Soda Pop started with a simple idea: what if yoga felt as fun and fizzy as your favorite soda? We wanted to create a world where kids couldn&apos;t wait to roll out their mats, and where music made every stretch feel like a dance.</p><p>From colorful pose cards to beats that pulse with energy, everything we make is designed to spark joy, build confidence, and get bodies moving.</p></div><div className="stat-grid">{stats.map(([n,l])=><article key={l}><strong>{n}</strong><span>{l}</span></article>)}</div></section>
  <section className="about-youtube"><small>▻ Subscribe on YouTube</small><h2>Find us on YouTube</h2><div><article><h3>Yoga Soda Pop</h3><b>@yogasodapop</b><p>Kids yoga, poses, and playful movement videos for all ages.</p><a href="https://youtube.com/@yogasodapop">▻ Subscribe</a></article><article><h3>Yoga Soda Pop Beats</h3><b>@yogasodapopbeats</b><p>Original music and beats to move, stretch, and vibe to.</p><a href="https://youtube.com/@yogasodapopbeats">▻ Subscribe</a></article></div></section>
  <section className="about-follow"><div className="insta-mark">◎</div><h2>Follow along</h2><h3>@yogasodapop</h3><p>Daily yoga inspiration, behind-the-scenes, and community love.</p><a href="https://instagram.com/yogasodapop">◎ Follow on Instagram</a></section>
  <section className="about-contact"><small>♡ Get in touch</small><h2>Say hello!</h2><p>Got a question, a collab idea, or just want to share some yoga joy? We&apos;d love to hear from you.</p><form action="mailto:yogasodapop@gmail.com" method="post" encType="text/plain"><label>Name<input name="name" placeholder="Your name"/></label><label>Email<input name="email" type="email" placeholder="Your email"/></label><label className="full">What&apos;s this about?<input name="subject" placeholder="General hello"/></label><label className="full">Message<textarea name="message" placeholder="Tell us what's on your mind..."/></label><button type="submit">➤ Send it!</button></form></section>
  <section className="about-cta"><small>♫ Keep the vibes going</small><h2>Ready to move &amp; groove?</h2><p>Explore our digital downloads, watch our YouTube channels, and join the Yoga Soda Pop community.</p><div><a href="/shop">Visit the Shop</a><a href="/kids">Kids Yoga</a><a href="/beats">Beats</a></div></section>
  <footer className="home-footer"><div className="footer-grid"><div><h3>🫧 Yoga Soda Pop</h3><p>Where yoga meets music and joy bubbles up! Two amazing worlds — Kids Yoga and Dance-Pop Beats.</p></div><div><h3>Explore</h3><a href="/kids">Yoga Soda Pop Kids</a><a href="/beats">Yoga Soda Pop Beats</a><a href="/shop">Shop</a><a href="/about">About</a></div><div><h3>Follow Along</h3><a href="https://youtube.com/@yogasodapop">▻ @yogasodapop</a><a href="https://instagram.com/yogasodapop">◎ @yogasodapop</a></div></div></footer>
</main>}
