import "./subpages.css";
import { SiteHeader, SiteFooter } from "./site-chrome";

type PageData={kicker:string;title:string;intro:string;sections:{title:string;body:string}[]};
const pages:Record<string,PageData>={
  "shipping-returns":{kicker:"SHOP WITH CONFIDENCE",title:"Shipping & Returns",intro:"The practical stuff, kept simple — so you know what to expect when your Yoga Soda Pop order is on its way.",sections:[{title:"Shipping",body:"We ship orders to the destinations available at checkout. Shipping options, estimated delivery times and costs are shown before you complete your purchase. Delivery estimates can vary by destination, carrier and busy holiday periods."},{title:"Tracking",body:"When tracking is available, you’ll receive the details using the contact information provided with your order. Please allow a little time for carrier tracking to update after dispatch."},{title:"Returns",body:"If something isn’t right, contact us at yogasodapop@gmail.com with your order details. We’ll review your request and explain the available return options. Items should be unused and in their original condition unless they arrived damaged or incorrect."},{title:"Questions?",body:"For shipping or return questions, contact yogasodapop@gmail.com and include your order number when possible."}]},
  "refund-policy":{kicker:"SHOP WITH CONFIDENCE",title:"Refund Policy",intro:"We want your Yoga Soda Pop order to arrive as expected. Here’s how to contact us if there is a problem.",sections:[{title:"Damaged or incorrect orders",body:"Please inspect your order when it arrives. If an item is damaged, defective or incorrect, email yogasodapop@gmail.com as soon as possible with your order information and photos where helpful."},{title:"Refund requests",body:"Refund eligibility depends on the circumstances of the order and the condition of the item. Contact us before sending anything back so we can review the request and provide the correct next steps."},{title:"Approved refunds",body:"When a refund is approved, it will be returned to the original payment method. Banks and payment providers may need additional processing time before the refund appears."}]},
  "privacy-policy":{kicker:"YOUR PRIVACY",title:"Privacy Policy",intro:"Yoga Soda Pop respects your privacy. This page explains the basic information we may receive when you shop, contact us or join the Pop Club.",sections:[{title:"Information you provide",body:"We may receive information you choose to provide, such as your email address, contact details and information needed to process an order."},{title:"How information is used",body:"Information may be used to fulfill purchases, provide customer support, send requested Pop Club updates, maintain site security and improve our services."},{title:"Service providers",body:"We may use service providers for website hosting, payments, order fulfillment, email delivery and analytics. They may process information only as needed to provide those services."},{title:"Your choices",body:"You can contact yogasodapop@gmail.com with privacy questions or requests relating to information you have provided to us."},{title:"Business",body:"Yoga Soda Pop is operated by Gamers4Gamers, LLC."}]},
  "terms":{kicker:"THE FINE PRINT",title:"Terms of Service",intro:"These terms cover use of the Yoga Soda Pop website and purchases made through our shop.",sections:[{title:"Using this site",body:"You may use this website for lawful personal shopping, viewing our content and contacting us. Please do not misuse the site, interfere with its operation or attempt unauthorized access."},{title:"Products and orders",body:"Product details, availability and pricing may change. An order is subject to acceptance and successful payment. We may correct accidental errors or cancel an order when fulfillment is not possible."},{title:"Creative content",body:"Yoga Soda Pop branding, original music, site design and original creative materials belong to their respective rights holders and may not be copied or commercially reused without permission."},{title:"Contact",body:"Questions about these terms can be sent to yogasodapop@gmail.com. Yoga Soda Pop is operated by Gamers4Gamers, LLC."}]}
};
export function InfoPage({type}:{type:keyof typeof pages}){const page=pages[type];return <main className="sub-page"><SiteHeader/><section className="sub-hero"><span className="sub-kicker">{page.kicker}</span><h1>{page.title}</h1><p>{page.intro}</p></section><section className="sub-content">{page.sections.map(s=><div key={s.title}><h2>{s.title}</h2><p>{s.body}</p></div>)}</section><SiteFooter/></main>}
