const seated = ["Road-trip bingo", "I Spy & color spotting", "Mazes and drawing", "Quiet breathing games"];
const stops = ["Five-minute movement break", "Copy Lumi yoga poses", "Hotel-room yoga", "Holiday memory journal"];

export default function TravelPage(){return <main className="travel-page">
  <header className="site-header"><a className="brand" href="/"><img src="/assets/yoga-soda-pop-logo-transparent.png" alt="Yoga Soda Pop" /></a><nav><a href="/">Home</a><a href="/kids">Kids</a><a className="active travel-active" href="/travel">Travel</a><a href="/beats">Beats</a><a href="/shop">Shop <span>Soon</span></a><a href="/about">About</a></nav></header>
  <section className="travel-hero"><div><p className="eyebrow orange">✈ Printable travel fun</p><h1>Lumi&apos;s Big<br/>Travel Adventure</h1><p>Screen-free games, creative activities, calming moments, and safe movement ideas for the journey and the trip itself.</p><div className="actions"><a className="button button-primary" href="#inside">See what&apos;s inside</a><a className="button button-secondary" href="/shop">Pack in development</a></div></div><div className="travel-passport"><span>TRAVEL PACK</span><strong>CAR<br/>PLANE<br/>TRAIN<br/>HOLIDAY</strong><b>with Lumi ✦</b></div></section>
  <section id="inside" className="travel-inside"><div className="section-heading"><h2>Busy on the way. Happy when you arrive.</h2><p>Activities are clearly grouped, so parents always know what is safe during travel and what is for a stop or destination.</p></div><div className="travel-columns"><article><span>🚗</span><h3>Safe while seated</h3>{seated.map(x=><p key={x}>✓ {x}</p>)}</article><article><span>🌴</span><h3>Rest stop, hotel &amp; holiday</h3>{stops.map(x=><p key={x}>✓ {x}</p>)}</article></div></section>
  <section className="travel-plan"><p className="eyebrow mint">Planned first edition</p><h2>Print only what your trip needs</h2><p>A4 and US Letter pages, printer-friendly options, a parent quick-pick guide, travel passport, activity pages, calm-down cards, and movement breaks.</p><a className="button button-primary" href="mailto:yogasodapop@gmail.com?subject=Tell%20me%20when%20Lumi%27s%20Travel%20Pack%20is%20ready">✉ Tell me when it launches</a></section>
  <footer className="home-footer"><div className="footer-grid"><div><h3>🫧 Yoga Soda Pop</h3><p>Movement, creativity, and calm for home and every adventure.</p></div><div><h3>Explore</h3><a href="/kids">Kids Yoga</a><a href="/travel">Travel Pack</a><a href="/beats">Beats</a><a href="/about">About</a></div><div><h3>Follow Along</h3><a href="https://youtube.com/@yogasodapop">▻ @yogasodapop</a><a href="https://instagram.com/yogasodapop">◎ @yogasodapop</a></div></div></footer>
</main>}
